name: Deploy Wistia Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Build Lambda Package
      run: |
        cd lambda
        zip -r ../lambda.zip .

    - name: Deploy Infrastructure
      run: |
        aws cloudformation deploy \
          --stack-name wistia-pipeline \
          --template-file infra/wistia_pipeline.yaml \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides LambdaZip=lambda.zip
