name: Wistia Data Pipeline CI/CD

on:
  push:
    branches: [ "main" ]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # -----------------------------------
    # Checkout repository
    # -----------------------------------
    - name: Checkout source
      uses: actions/checkout@v4

    # -----------------------------------
    # Setup Python
    # -----------------------------------
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # -----------------------------------
    # Install dependencies & lint
    # -----------------------------------
    - name: Install dependencies
      run: |
        pip install flake8
        pip install -r lambda/requirements.txt

    - name: Run linting
      run: |
        flake8 lambda --max-line-length=120

    # -----------------------------------
    # Package Lambda
    # -----------------------------------
    - name: Build Lambda ZIP
      run: |
        cd lambda
        zip -r ../lambda.zip .

    # -----------------------------------
    # Configure AWS Credentials
    # -----------------------------------
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # -----------------------------------
    # Upload Lambda ZIP to S3
    # -----------------------------------
    - name: Upload Lambda package
      run: |
        aws s3 mb s3://${{ secrets.S3_BUCKET }}
        aws s3 cp lambda.zip s3://${{ secrets.S3_BUCKET }}/lambda/lambda.zip

    # -----------------------------------
    # Deploy CloudFormation Stack
    # -----------------------------------
    - name: Deploy Infrastructure
      run: |        
        
        aws cloudformation delete-stack --stack-name wistia-pipeline --region us-west-1

        aws cloudformation wait stack-delete-complete --stack-name wistia-pipeline --region us-west-1

        aws cloudformation validate-template \
          --template-body file://infra/wistia_pipeline.yaml
          
        aws cloudformation deploy \
          --stack-name wistia-pipeline \
          --template-file infra/wistia_pipeline.yaml \
          --parameter-overrides DataLakeBucketName=${{ secrets.S3_BUCKET }} \
          --capabilities CAPABILITY_NAMED_IAM

    # -----------------------------------
    # Upload PySpark Job
    # -----------------------------------
    - name: Upload PySpark job
      run: |
        aws s3 cp pyspark/transform_wistia.py \
        s3://${{ secrets.S3_BUCKET }}/jobs/transform_wistia.py

